version: "3"

services:
  mysql-database-service:
    image: mysql
    container_name: mysql-container
    ports:
      - "3307:3306"
    networks: [ speedybite-app-network ]
    environment:
      MYSQL_ROOT_PASSWORD: ashutosh
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongo-database-service:
    image: mongo
    container_name: mongodb-database-container
    ports:
      - "27018:27017"
    networks: [ speedybite-app-network ]

  user-auth-service:
    build: UserAuth/
    container_name: user-auth-service-container
    ports:
      - "8081:8081"
    networks: [ speedybite-app-network ]
    depends_on: [ mysql-database-service ]
    restart: always

  user-service:
    build: UserService/
    container_name: user-service-container
    ports:
      - "8082:8082"
    networks: [ speedybite-app-network ]
    depends_on: [ mongo-database-service ]
    restart: always

  restaurant-service:
    build: /RestaurantService
    container_name: restaurant-service-container
    ports:
      - "8083:8083"
    networks: [ speedybite-app-network ]
    depends_on: [ mongo-database-service ]
    restart: always

  order-service:
    build: /OrderService
    container_name: order-service-container
    ports:
      - "8084:8084"
    networks: [ speedybite-app-network ]
    depends_on: [ mongo-database-service ]
    restart: always

  payment-service:
    build: /PaymentService
    container_name: payment-service-container
    ports:
      - "8085:8085"
    networks: [ speedybite-app-network ]
    restart: always

  api-gateway:
    build: /APIGateway
    container_name: api-gateway-container
    ports:
      - "9000:9000"
    networks: [ speedybite-app-network ]

networks:
  speedybite-app-network:
    driver: bridge