server:
  port: 8761

spring:
  application:
    name: eureka-server-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka-server-service

