spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://mongodb-database-container:27017/OrderDb
      port: 27017
      database: OrderDb

server:
  port: 8084
  error:
    include-message: always
