spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://mongodb-database-container:27017/OrderDb
      port: 27017
      database: OrderDb

server:
  port: 8084
  error:
    include-message: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka